Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-2, pull requests merged in 2023-05, with the labels that each got.

#8 jessica-added backend code for toggleDriver backend
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
Labels: Merge Candidate - testing on staff-qa

#25 jessica replace email with name in navbar
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5

#32 pc - update workflow 33 to publish stryker report even if coverage is below 100%
  .github/workflows/33-frontend-pr-mutation-testing.yml
Labels: staff
