Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-2, pull requests merged in 2023-06, with the labels that each got.

#59 Pc update workflows
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
  .github/workflows/52-storybook-main-branch.yml
  .github/workflows/54-storybook-pr.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: staff

#16 Leon fix bug with user role updates in session using interceptor
  .github/workflows/13-backend-incremental-pitest.yml
  src/main/java/edu/ucsb/cs156/gauchoride/Interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/gauchoride/Interceptors/RoleUserInterceptorAppConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/UserRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/Interceptors/RoleUserInterceptorTests.java
  src/test/java/edu/ucsb/cs156/gauchoride/testconfig/MockCurrentUserServiceImpl.java
Labels: 10

#27 Page not found cheryl
  frontend/src/App.js
  frontend/src/main/pages/PageNotFound.js
  frontend/src/tests/pages/PageNotFound.test.js
Labels: 10

#55 jessica add controller files for driver shift table backend
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverShift.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverShiftRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverShiftControllerTests.java
Labels: 10

#56 Tim add rider toggle button
  frontend/package-lock.json
  frontend/package.json
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminUsersPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/User.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/UsersControllerTests.java
Labels: 10

#64 Leon update links to prod and qa sites in README
  README.md
Labels: 5

#24 Simon-Add CRUD Utilities & Backend Operations for Cart
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/CartController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Cart.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/CartRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/CartControllerTests.java
Labels: FIXME: Changes Requested

#62 ARR - Added POST/GET for ride requests
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/errors/IllegalRequestException.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideControllerTests.java
Labels: 10

#30 Leon chatroom backend entity and POST/GET APIs
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverChatController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverChat.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverChatRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverChatControllerTests.java
Labels: 10
